title: Java2.0
description: JAVA2.0  is  invented  in  WEB by  wilmix  jemin j  at  year  2016  and it  consists  of  25  modules  simillar  to  Remotewebappilcation  SKY  P.L  WEB.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
